name: Windows Build

on:
  workflow_dispatch:

env:
  NJOBS: 4

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      COMPILER: gcc
      TARGET_ARCH: x86_64
      DAILY_BUILD: 1
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          ccache
          clang
          cmake
          git
          make
          pkgconf
          python3
          unzip
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-ccache
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ffmpeg
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-portaudio
          mingw-w64-x86_64-qt6
    - name: Build
      run: ./ports/ci/windows-msys/build.sh
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: webcamoid-windows-x86_64
        path: webcamoid-data-gcc-x86_64/
        if-no-files-found: error